Refactor/5
f-teamdev/ship pull request #20
Opened 2022-08-18 14:45 UTC by ericqueirozc

Nesse PR foi corrigido alguns erros de digitação, lint e remoção de comentários gerados pelo Flutter que não agregavam ao código.

2022-08-19 14:41 UTC, BlackLeg15 commented on dashboard/.fvm/flutter_sdk
> +C:/Users/paulo/fvm/versions/3.0.5
Adiciona este arquivo ao `.gitignore`

2022-08-19 14:41 UTC, BlackLeg15 commented on dashboard/android/app/build.gradle
> +    compileSdkVersion 31
O mais recente é o 33, recomendo.

2022-08-19 14:43 UTC, BlackLeg15 commented on dashboard/.vscode/settings.json
> +    "dart.flutterSdkPath": "C:\\Users\\paulo\\fvm\\versions\\3.0.5"
É interessante remover esses caminhos relativos dos devs.

2022-08-19 14:44 UTC, BlackLeg15 commented on dashboard/lib/app/modules/auth/auth_page.dart
> +                          credentials.password.validate().fold(id, (r) => null),
Verificar a possibilidade de fixar o tamanho máximo das linhas para o projeto.

2022-08-19 14:48 UTC, BlackLeg15 commented on dashboard/.fvm/flutter_sdk
> +C:/Users/paulo/fvm/versions/3.0.5
Adicionar este arquivo ao `.gitignore`.

2022-08-19 14:48 UTC, BlackLeg15 requested changes
Fiz alguns comentários. Ademais, bom trabalho.

2022-08-20 22:37 UTC, ericqueirozc commented on dashboard/lib/app/modules/auth/auth_page.dart
> +                          credentials.password.validate().fold(id, (r) => null),
Tamanho máximo de linhas devidamente ajustado

2022-08-22 12:13 UTC, BlackLeg15 commented on dashboard/android/app/build.gradle
> +    compileSdkVersion 31
Ninja. Muda a targetVersion pra 33 também.

2022-08-22 12:14 UTC, BlackLeg15 commented on dashboard/lib/app/modules/auth/auth_page.dart
> +                          credentials.password.validate().fold(id, (r) => null),
Como exatamente tu fez isso?

2022-08-22 14:03 UTC, ericqueirozc commented on dashboard/lib/app/modules/auth/auth_page.dart
> +                          credentials.password.validate().fold(id, (r) => null),
Fiz a configuração no arquivo de workspace do projeto, na parte de settings

2022-08-22 14:06 UTC, BlackLeg15 approved these changes

2022-08-22 14:08 UTC, BlackLeg15 commented
@AlvaroVasconcelos Feito ✅

2022-08-22 16:39 UTC, merged